stages:
  - test
  - build


unit:
  stage: test
  image: registry.gitlab.com/mbarkhau/markdown-katex/base
  script:
    - make lint
    - make mypy
    - make test
  coverage: '/^(TOTAL|src).*?(\d+\%)$/'
  artifacts:
    paths:
      - htmlcov/
      - mypycov/
  allow_failure: false


pages:
  stage: build
  script:
    - mkdir -p public/cov
    - mkdir -p public/mypycov
    - cp -r htmlcov/* public/cov/
    - cp -r mypycov/* public/mypycov/
  artifacts:
    paths:
      - public
  only:
    - master
